on:
  push:
    branches:
      - master

name: Deploy to STG

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run test
